//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainerManagementSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentEntertainerContracts = new HashSet<AgentEntertainerContract>();
        }
    
        public int Agent_ID { get; set; }
        public string Agent_fName { get; set; }
        public string Agent_lName { get; set; }
        public decimal Agent_salary { get; set; }
        public System.DateTime Agent_hiringDate { get; set; }
        public int FK_agencyOfficeID { get; set; }
    
        public virtual AgencyOffice AgencyOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentEntertainerContract> AgentEntertainerContracts { get; set; }
        public virtual AgentContactInformation AgentContactInformation { get; set; }
    }
}
