//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainerManagementSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentEntertainer
    {
        public string Agent_fName { get; set; }
        public string Agent_lName { get; set; }
        public string Entertainer_name { get; set; }
    }
}
