//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainerManagementSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntertainerGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntertainerGroup()
        {
            this.EntertainerMembers = new HashSet<EntertainerMember>();
        }
    
        public int EntertainerGroup_ID { get; set; }
        public string Entertainer_name { get; set; }
        public Nullable<int> FK_contractID { get; set; }
        public Nullable<int> FK_styleID { get; set; }
        public bool EntertainmentGroup_active { get; set; }
    
        public virtual AgentEntertainerContract AgentEntertainerContract { get; set; }
        public virtual Style Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntertainerMember> EntertainerMembers { get; set; }
    }
}
