//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainerManagementAspNetMcv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Address_ID { get; set; }
        public string Address_address { get; set; }
        public string Address_addressBuilding { get; set; }
        public short Address_addressNo { get; set; }
        public Nullable<byte> Address_addressNoRange { get; set; }
        public string Address_city { get; set; }
        public string Address_zipcode { get; set; }
        public string Address_country { get; set; }
    
        public virtual AgencyOffice AgencyOffice { get; set; }
    }
}
